<?php

/**
 * @file
 * Functions to support theming in the opin-base theme.
 */

/**
* Implements hook_preprocess_html()
*/

// Add node id to the body classes
function opin_base_preprocess_html(&$variables) {

  //Add a language to the body class.
  $variables['language'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $node = \Drupal::routeMatch()->getParameter('node');
    if($node) {
    $variables['attributes']['class'][] = 'path-node-' . $node->id();
  }
}

